-- MySQL Script generated by MySQL Workbench
-- Ter 31 Mar 2015 01:32:12 BRT
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema ebd
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema ebd
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ebd` DEFAULT CHARACTER SET latin1 COLLATE latin1_swedish_ci ;
USE `ebd` ;

-- -----------------------------------------------------
-- Table `ebd`.`trimestre`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ebd`.`trimestre` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(32) NOT NULL,
  `inicio` DATE NOT NULL,
  `fim` DATE NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ebd`.`aula`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ebd`.`aula` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `data` DATE NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ebd`.`classe`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ebd`.`classe` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `idade_min` INT(2) NOT NULL,
  `idade_max` INT(2) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ebd`.`tipo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ebd`.`tipo` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(32) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ebd`.`membro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ebd`.`membro` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(128) NOT NULL,
  `telefone` VARCHAR(32) NULL,
  `nascimento` DATE NULL,
  `tipo_id` INT NOT NULL,
  `classe_id` INT NOT NULL,
  PRIMARY KEY (`id`, `tipo_id`, `classe_id`),
  INDEX `fk_membro_tipo1_idx` (`tipo_id` ASC),
  INDEX `fk_membro_classe1_idx` (`classe_id` ASC),
  CONSTRAINT `fk_membro_tipo1`
    FOREIGN KEY (`tipo_id`)
    REFERENCES `ebd`.`tipo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_membro_classe1`
    FOREIGN KEY (`classe_id`)
    REFERENCES `ebd`.`classe` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ebd`.`classe_trimestre`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ebd`.`classe_trimestre` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `classe_id` INT NOT NULL,
  `trimestre_id` INT NOT NULL,
  PRIMARY KEY (`id`, `classe_id`, `trimestre_id`),
  INDEX `fk_classe_has_trimestre_trimestre1_idx` (`trimestre_id` ASC),
  INDEX `fk_classe_has_trimestre_classe1_idx` (`classe_id` ASC),
  CONSTRAINT `fk_classe_has_trimestre_classe1`
    FOREIGN KEY (`classe_id`)
    REFERENCES `ebd`.`classe` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_classe_has_trimestre_trimestre1`
    FOREIGN KEY (`trimestre_id`)
    REFERENCES `ebd`.`trimestre` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ebd`.`frequencia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ebd`.`frequencia` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `membro_id` INT NOT NULL,
  `aula_id` INT NOT NULL,
  PRIMARY KEY (`id`, `membro_id`, `aula_id`),
  INDEX `fk_membro_has_aula_aula1_idx` (`aula_id` ASC),
  INDEX `fk_membro_has_aula_membro1_idx` (`membro_id` ASC),
  CONSTRAINT `fk_membro_has_aula_membro1`
    FOREIGN KEY (`membro_id`)
    REFERENCES `ebd`.`membro` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_membro_has_aula_aula1`
    FOREIGN KEY (`aula_id`)
    REFERENCES `ebd`.`aula` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ebd`.`aula_classe`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ebd`.`aula_classe` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `aula_id` INT NOT NULL,
  `classe_trimestre_id` INT NOT NULL,
  PRIMARY KEY (`id`, `aula_id`, `classe_trimestre_id`),
  INDEX `fk_aula_has_classe_trimestre_classe_trimestre1_idx` (`classe_trimestre_id` ASC),
  INDEX `fk_aula_has_classe_trimestre_aula1_idx` (`aula_id` ASC),
  CONSTRAINT `fk_aula_has_classe_trimestre_aula1`
    FOREIGN KEY (`aula_id`)
    REFERENCES `ebd`.`aula` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_aula_has_classe_trimestre_classe_trimestre1`
    FOREIGN KEY (`classe_trimestre_id`)
    REFERENCES `ebd`.`classe_trimestre` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ebd`.`escala`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ebd`.`escala` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `membro_id` INT NOT NULL,
  `aula_classe_id` INT NOT NULL,
  PRIMARY KEY (`id`, `membro_id`, `aula_classe_id`),
  INDEX `fk_membro_has_aula_membro2_idx` (`membro_id` ASC),
  INDEX `fk_escala_aula_classe1_idx` (`aula_classe_id` ASC),
  CONSTRAINT `fk_membro_has_aula_membro2`
    FOREIGN KEY (`membro_id`)
    REFERENCES `ebd`.`membro` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_escala_aula_classe1`
    FOREIGN KEY (`aula_classe_id`)
    REFERENCES `ebd`.`aula_classe` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
